#!/usr/bin/python
from sys import argv
script, filename=argv
print(f"We are going to erase {filename}.")
print("If you don't want that, hit ctrl-C(^C).")
print("To continue, hit RETURN")
input("?")
print("Opening the file.......")

target=open(filename, 'w')
print("Truncating the file.... Goodby 1")
target.truncate()
print("Now I'm going to ask you to enter three lines")
line1=input("Line 1 : ")
line2=input("line 2 : ")
line3=input("line 3 : ")
print("I am going to write these to the file.")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")
print("And finally we are closing it.")
target.close()
